services:
  postgres-auth:
    image: postgres:15
    container_name: authenticationservice-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - authenticationservice-network

  app-auth:
    build: .
    container_name: authenticationservice-app
    depends_on:
      - postgres-auth
    environment:
      AUTH_DB_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      AUTH_DB_USERNAME: postgres
      AUTH_DB_PASSWORD: postgres
      USER_SERVICE_URL: http://192.168.100.17:8080
      JWT_SECRET: mySecretKeyForJWTTokenGeneration2025!VeryLongAndSecure
      JWT_ACCESS_EXPIRATION: 900000
      JWT_REFRESH_EXPIRATION: 604800000
    ports:
      - "8082:8082"
    networks:
      - authenticationservice-network

volumes:
  postgres_auth_data:

networks:
  authenticationservice-network:
    driver: bridge
